messages:
  help:
    - "&6------ &3Commands &6------"
    - "&3/help - Shows the commands."
    - "&3/kill - Kill yourself."
    - "&3/msg - Message a player."
    - "&3/ignore - Ignores a player in chat."
    - "&3/stats - Shows the server stats."
    - "&6----------------------"

commands:
  enabled: true

crystal:
  place_delay_millis: 100
  explosion_delay_ticks: 4
  explosion_power: 6.0

defaultConfig:
  announcement:
    enabled: false
    message: ""