name: core
version: '${version}'
main: eu.felicianware.core.Main
api-version: '1.20'
folia-supported: true
commands:
  help:
    description: Display server commands.
    usage: /help
  discord:
    description: Display the Discord servers invite
    usage: /discord
  kill:
    description: Kills you
    usage: /kill